### PR TITLE
WIP: Region Page Shipment Totals & Formatting

### LINKED ISSUE #24: Display Shipment Totals on Region Template Pages
**Previous work:** add content to the regions listing (index page) and to each region page (templates).

- Index page now displays each region, along with a thumbnail of a map of the region.
- Template page now displays region information (name + full-image map) and a table of shipment data, including icons describing the category of the ship.

**Starting Point:** https://app.codesee.io/shared/eda14600-0681-11ec-bcdf-b35d3087a4b1

**Goals:**

- [x] Show the totals for relevant columns as a bottom row in the table: `# of shipments`, `commercial value`, `weight`, `distance`, `C02`.
- [x] Reach: Pull the totals out into a more stylized summary above the table, to highlight our impact.
- [ ] Evaluate additional ways to display the totals (see issue).
- [ ]  Slight number formatting. Possibly look at browser region to format based on user locale.

### LINKED ISSUE #25: Style the Region Template Page
**Previous work:** add content to the regions listing (index page) and to each region page (templates).

- Index page now displays each region, along with a thumbnail of a map of the region.
- Template page now displays region information (name + full-image map) and a table of shipment data, including icons describing the category of the ship.

**Starting Point:** https://app.codesee.io/shared/eda14600-0681-11ec-bcdf-b35d3087a4b1

**Goal:**

- [x] Add cell spacing.  Alternate row background colors.

### PR DESCRIPTION
**Pull request by jtfairbank**
For #24 

**Progress:**

- Starting State - https://app.codesee.io/data-flow/eda14600-0681-11ec-bcdf-b35d3087a4b1
- Totals Calculations - https://app.codesee.io/data-flow/6f76d030-0684-11ec-a147-99247f31a8fe
- Display Totals - https://app.codesee.io/data-flow/5192b970-0685-11ec-a048-c194ae19f5d1

**Next Up:**

- [ ] Evaluate additional ways to display the totals (see issue).
- [ ] Slight number formatting.  Possibly look at browser region to format based on user locale.

### CODE REVIEW

**Comment by jtfairbank** [comment]
@ramonh I think we made some decent progress here but wanted to wrap a few things up.  Think we can finish this off sometime before / during our next stream?  Or alternatively is there enough documentation on the Issue / PR to open it up to a Hacktoberfest contributor?

**Comment by hola-soy-milk** [comment]
Good call! What do you think about renaming this PR and merging as-is? I can help with that

**Comment by jtfairbank** [comment]
@ramonh fine by me!

**Comment by hola-soy-milk** [comment]
Great! I'll do a pass through and document what's changed properly

**Comment by hola-soy-milk** [comment]
Closed for rebase, reopened as #65

**Pull request closed without merging**
