### PR TITLE
Fixed CodeSee link in ReadMe

### LINKED ISSUE #550: Codesee link not working in README
Hey all! 

Codesee link not working in README https://docs.codesee.io/docs/codebase-maps

image
image

### PR DESCRIPTION
**Pull request by eyetech2dev**
Resolves #550 
I updated the CodeSee link in ReadMe with the new one as provided by @jtfairbank

### CODE REVIEW

**Comment by jtfairbank** [comment]
Thanks for the PR @eyetech2dev!  Do you mind also adding your name to the `/CONTRIBUTORS.md` file?

**Comment by eyetech2dev** [comment]
Thank you, I have add my name to the contributer list. This is my first time contributing to open source, I hope I did it correctly! Feedback is welcome :)

**Comment by jtfairbank** [comment]
That was perfect @eyetech2dev, I'm very impressed!  Looks like we're having an issue with our Netlify deploy previews, I'll need to look into that tomorrow and then I can merge this in.  :)

**Review by jtfairbank — APPROVED** [review]

**Review by hola-soy-milk — APPROVED** [review]
Looks fantastic, thank you!

**Pull request merged**
