### PR TITLE
Setup Generic Page Skeleton

### PR DESCRIPTION
**Pull request by jtfairbank**
Relates to #709 

This PR should provide a skeleton for making generic pages using our Page > Sections > Content Blocks strategy:

- [x] transform all generic page markdown node to `DAPageGeneric` nodes
- [x] create a generic page template which uses `SimpleLayout` and renders content sections
- [x] create a Section component which renders content blocks, using existing components
- [x] unit & e2e tests

### CODE REVIEW

**Comment by jtfairbank** [comment]
Hey @raae I'm having some trouble with this one.  I added a new gatsby transformer (Remark > DAPageGeneric), along with custom types that use unions to handle the different content blocks.  However I get an error when writing a query for this content and I'm not sure what I'm doing wrong.  Can you help me debug?  Happy to pair up if you want to jump on a zoom!

Relevant files:

- `defineGenericPageTypes` function in  `/gatsby/customize-schema.ts`
- `createGenericPagesFromMarkdown` function in `/gatsby/transform-nodes.ts`


### Example Query

```
query Query {
  allDaPageGeneric {
    nodes {
      title
      slug
      sections {
        blocks {
          ... on DAPageBlockTitle {
            __typename
            text
          }
          ... on DAPageBlockText {
            __typename
            text
          }
        }
      }
    }
  }
}
```

### Error

```
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'type')",
      "locations": [
        {
          "line": 7,
          "column": 9
        }
      ],
      "path": [
        "allDaPageGeneric",
        "nodes",
        0,
        "sections",
        1,
        "blocks",
        0
      ],
      "extensions": {
        "stack": [
          "TypeError: Cannot read properties of undefined (reading 'type')",
          "    at /home/jtfairbank/Documents/distribute-aid/distributeaid.org/node_modules/gatsby/src/schema/schema.js:436:57",
          "    at completeAbstractValue (/home/jtfairbank/Documents/distribute-aid/distributeaid.org/node_modules/graphql/execution/execute.js:672:21)",
          "    at completeValue (/home/jtfairbank/Documents/distribute-aid/distributeaid.org/node_modules/graphql/execution/execute.js:584:12)",
          "    at /home/jtfairbank/Documents/distribute-aid/distributeaid.org/node_modules/graphql/execution/execute.js:620:25",
          "    at Array.map (<anonymous>)",
          "    at safeArrayFrom (/home/jtfairbank/Documents/distribute-aid/distributeaid.org/node_modules/graphql/jsutils/safeArrayFrom.js:36:23)",
          "    at completeListValue (/home/jtfairbank/Documents/distribute-aid/distributeaid.org/node_modules/graphql/execution/execute.js:607:53)",
          "    at completeValue (/home/jtfairbank/Documents/distribute-aid/distributeaid.org/node_modules/graphql/execution/execute.js:572:12)",
          "    at resolveField (/home/jtfairbank/Documents/distribute-aid/distributeaid.org/node_modules/graphql/execution/execute.js:472:19)",
          "    at executeFields (/home/jtfairbank/Documents/distribute-aid/distributeaid.org/node_modules/graphql/execution/execute.js:292:18)",
          "    at collectAndExecuteSubfields (/home/jtfairbank/Documents/distribute-aid/distributeaid.org/node_modules/graphql/execution/execute.js:748:10)",
          "    at completeObjectValue (/home/jtfairbank/Documents/distribute-aid/distributeaid.org/node_modules/graphql/execution/execute.js:738:10)",
          "    at completeValue (/home/jtfairbank/Documents/distribute-aid/distributeaid.org/node_modules/graphql/execution/execute.js:590:12)",
          "    at completeValue (/home/jtfairbank/Documents/distribute-aid/distributeaid.org/node_modules/graphql/execution/execute.js:556:21)",
          "    at /home/jtfairbank/Documents/distribute-aid/distributeaid.org/node_modules/graphql/execution/execute.js:620:25",
          "    at Array.map (<anonymous>)"
        ]
      }
    },
  ...
]
```

**Comment by raae** [comment]
This week I cannot help, but end of next week I can.

**Comment by jtfairbank** [comment]
Hey @coderbyheart @JasonFritsche I'm having some trouble mocking `Math.random()` in `/src/utils/site-theme.spec.ts`.  Any ideas how to mock these sort of globals with Jest?

**Comment by coderbyheart** [comment]
Use [spyOn](https://jestjs.io/docs/jest-object#jestspyonobject-methodname): `jest.spyOn(Math, 'random').mockReturnValue(0.123456789);`

**Comment by jtfairbank** [comment]
Hey @coderbyheart it seems like that's what I'm trying to do already but I can't figure out why it's not working?  Maybe I messed up the implementation or something?

https://github.com/distributeaid/distributeaid.org/blob/7b84bab46f4a3ba95236dcbd11375aaa20c8843b/src/utils/site-theme.spec.ts#L33-L36

**Comment by coderbyheart** [comment]
The problem was that you were not setting the `randomize` parameter. But it makes more sense to separate the concerns and using shuffle from lodash to randomize the array when needed.

**Comment by jtfairbank** [comment]
@coderbyheart ah good catch, thanks so much for the improvements in your commit!

**Comment by coderbyheart** [comment]
Made a few changes to the naming, tests and removed unrelated changes (will re-add in saga)

**Pull request merged**
