### PR TITLE
Add e2e tests for routes pages

### LINKED ISSUE #815: Add E2E test for Routes pages
### Description

Please see the second point in this comment for more info: https://github.com/distributeaid/distributeaid.org/pull/791#pullrequestreview-1152337107 

### Front end feature screenshots

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Myrfion**
Implement two e2e tests for both France and Lebanon routes.
These tests are: 
- Check if the page has a correct title
- Check if page include all proper headers for sections

### CODE REVIEW

**Comment by Myrfion** [comment]
#815

**Comment by Myrfion** [comment]
Hmm, e2e tests failed on the pipeline even tho everything works well on my side, could it be something wrong with the CI?

**Comment by jtfairbank** [comment]
Hey @Myrfion thanks so much for contributing!  You're right that our CI is having some issues, I'm going to try to work them thru and push to this branch.

In the meantime, could you add your name to the `/CONTRIBUTORS.md` file in a commit?

**Comment by Myrfion** [comment]
Hello @jtfairbank done :) Thank you for letting me to make the contribution

**Review by jtfairbank — APPROVED** [review]

**Comment by jtfairbank** [comment]
Great collabing with you on this one @Myrfion!  We have OSS coding events each week, including code jams and a live stream.  Should be putting November's schedule up tomorrow!  [https://opencollective.com/distribute-aid-usa/events](https://opencollective.com/distribute-aid-usa/events)

Hope to see you around!

**Pull request merged**
