### PR TITLE
Migrate build & config files to TypeScript

### LINKED ISSUE #618: Migrate Gatsby from JS to TypeScript
Gatsby added build-side support for TypeScript in March '22.  It'd be nice to use TypeScript consistently throughout our codebase.  

### Documentation

  * Gatsby JS > TypeScript - https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript/#migrating-to-typescript
  * Gatsby Unit Testing TypeScript Setup - https://www.gatsbyjs.com/docs/how-to/testing/unit-testing/#using-typescript
  * CodeSee Map of relevant files to migrate - https://app.codesee.io/maps/public/577b1d60-3306-11ed-af0d-b58e3b81aea3

### Checklist

- [ ] Sign the `/CONTRIBUTORS.md` file if this is your first contribution.
- [ ] Install dependencies.
- [ ] Migrate gatsby build files config files to TypeScript.
- [ ] Migrate other config / top-level files to TypeScript if possible (may depend on TypeScript support from the package that uses them).
- [ ] Document any files that couldn't be migrated (and why) in this issue.
- [ ] Resolve any type issues in the migrated files.
- [ ] Run tests to ensure the site isn't broken.

### PR DESCRIPTION
**Pull request by fredericbonnet**
Closes #618 

JS files that weren't migrated:

- `.babelrc.js`, `jest-preprocess.js`: Babel files only support JS
- `postcss.config.js`: PostCSS doesn't supports TS config files
- `.prettierrc.js`: Prettier doesn't support TS config files

JS files that were type-annotated:

- `tailwind.config.js`: Tailwind doesn't support TS but provides type definitions that can be used for type checking. on JS files This helped spot an issue with `config.theme.extend.fontFamily.sans` that expected an array of strings but was given a comma-separated string.

Migrated Gatsby files:

- `gatsby-browser.tsx`, `gatsby-config.ts`, `gatsby-node.ts`: main config files
- `gatsby/`
  - `create-pages.ts`, `customize-schema.ts`: migrated without issues, added function signatures and type definitions
  - `create-resolvers.ts`, `transform-nodes.ts`: added function signatures and type definitions, only minor issues remain due to the lack of relevant type definitions.

### CODE REVIEW

**Review by coderbyheart — CHANGES_REQUESTED** [review]
- e2e tests must pass
- prettier supports TS. [Example TS codebase with prettier.](https://github.com/distributeaid/needs-assessment-storage/blob/18adb2e80eb63f1eeb99568184d3fbe84ab55d7d/package.json#L104)

**Comment by fredericbonnet** [comment]
To clarify about Prettier: it's only the config file that needs to be JS, Prettier works just fine with TS codebases. I've updated the PR description accordingly.

I'll take a look at the E2E failures.

**Comment by fredericbonnet** [comment]
After investigation it seems that the E2E test failure is a GitHub action issues. The **Run the end-to-end test** job depends on an artifact generated by the **build** job, namely the `public` directory generated by `yarn build`. However the compiled `gatsby-(config|node).js` and dependencies are in the `.cache` directory that is not copied over, hence the failure at `yarn serve` startup.

Possible solutions are:
1. Run `yarn build` from the **Run the end-to-end test** job, don't copy artifacts from **build**
    - Pros: clean slate for a more reliable result
    - Cons: job will take longer
2. Copy the whole `.cache` dir between jobs
    - Pros: simple
    - Cons: cache dir can be large (319MB on my machine), not sure if it can be copied from one container to another
3. Copy only the necessary files
    - Pros: only a handful files are needed: `.cache/compiled/gatsby-config.js`, `.cache/compiled/gatsby-node.js`, `match-paths.json`
    - Cons: we might miss some dependencies

**Comment by coderbyheart** [comment]
Without having a look, 2. sounds like a good and simple solution

**Comment by fredericbonnet** [comment]
Option #2 fixed the E2E test issues!

**Comment by coderbyheart** [comment]
Great work!

**Comment by coderbyheart** [comment]
Great work!

**Pull request merged**
