### PR TITLE
Upgrade CodeSee workflow to version 2

### PR DESCRIPTION
**Pull request by cubes**
[CodeSee](https://codesee.io) is a code visibility platform. 

This change updates the CodeSee workflow file to the latest version for security, maintenance, and support improvements (see changelog below).

That workflow file:

  - runs CodeSee's code analysis on every PR push and merge
  - uploads that analysis to CodeSee. 
  - _It does __not__ transmit your code._

The code analysis is used to generate maps and insights about this codebase.

CodeSee workflow changelog:

  - Improved security: Updates permission to be read-only.
  - Improved future maintenance: Replaces the body of the workflow with a single github action: [codesee-action](https://github.com/Codesee-io/codesee-action). This makes it significantly easier for CodeSee to introduce future improvements and fixes without requiring another PR like this.
  - Improved Python support: The action now properly supports Python 3.11, and will continue to support new Python versions as they are released.

### CODE REVIEW

**Comment by jleven** [comment]
@jtfairbank -- I noticed that automated tests failed on this PR. Is there something about this change that caused tests to fail, or is it possible these test failures are a flake?

**Comment by jtfairbank** [comment]
Hey @jleven and @cubes so sorry for the delay here, been out with the flu most of the week.  Feedback using [conventional comments](https://conventionalcomments.org/):

  * praise: This looks awesome!  Was wondering when you'd switch to a github action based workflow.
  * chore: @cubes would you mind adding your name to our `CONTRIBUTORS.md` file?  It's a standard part of our first-time contributor process to ensure everyone agrees to our community guidelines and sort out OSS copyright confusion.  I know it's a bit silly for such a minor change but just want to keep things consistent.
  
@jleven you're right that there are some flaky tests.  Run into timeout issues on some CI runs, which looks to be the case here.

**Comment by cubes** [comment]
@jtfairbank per your request, I have added myself to `CONTRIBUTORS.md`. Please advise if there's anything else I need to do to make this ready for merging?

**Review by jtfairbank — APPROVED** [review]

**Comment by jtfairbank** [comment]
All good @cubes!  Thanks again!

**Pull request merged**
