### PR TITLE
use aliases in gatsby and typescript

### LINKED ISSUE #11: Set up path aliases
It would be nice to import components using path aliases. For example: `import Nav from '@components/Nav'`.

Gatsby has a plugin for it, and we'll also need to set up a `tsconfig.json` file to make TypeScript aware of the paths.

### PR DESCRIPTION
**Pull request by mslourens**
This PR introduces aliases for components, layouts, types and pages. I couldn't run the application itself because I don't have the contentful queries and content, but I think it should work like this. If please, please give me some tokens, so I can run the application locally.

### CODE REVIEW

**Comment by khendrikse** [comment]
This would close #11 I think

**Comment by jtfairbank** [comment]
@mslourens This looks wonderful!  Really appreciate the PR and my bad for not reviewing sooner (been a bit hectic this month on the aid logistics front).  I'm curious- how did you find out about Distribute Aid and our landing site project?

A few notes and next steps:

- [ ] Merge or rebase the latest version of `saga` into this branch.  @ramonh and I resolved issue #38 with PR #39 today, regarding Contentful access.  Once you have the latest from `saga` merged in run  `yarn install` then `yarn dev` to build the site locally using the read-only access token that's now committed to the repo.  Please let me know if you run into issues with the new process.
- [ ] Check for additional includes to convert based on any changes / additions in `saga` that were made after you created this PR.
- [ ] Include a commit that adds your name to the `CONTRIBUTORS.md` file.
- [ ] Please tag me when you're ready for a final review & the PR to be merged!

**Comment by jtfairbank** [comment]
@ramonh is it possible for @mslourens to get a CodeSee map showing the changes / additions between this branch and the latest code in `saga`?  This would help him identify where to check for additional imports to update, and would help me on the reviewing end to identify potential conflicts or other issues between the two branches when I'm reviewing.

It's a bit more advanced then the Pull Request maps since it's really a 3-way comparison between the latest in `saga`, the latest here, and the shared base state in there history of the commit where the branches diverged.  Related: it'd be helpful if the maps could show more detailed info: changed in `saga`, changed here, or changed in both (potential conflict!).  Same for added / removed / moved files.

**Comment by mslourens** [comment]
@jtfairbank I came across your project by searching for javascript projects which need some help. I always do this when I have some spare time on my hands, but this month I reserved some more time for the #hacktoberfest. I especially like your project because it's for a good cause: helping people in need.

**Comment by jtfairbank** [comment]
That's awesome!  And I'm glad you think we're making that IRL difference.  As a maintainer I'm having a bit of a hard time finding the time to get more issues up that are good for Hacktober fest.  If you have the time, I'd love to send you a link to our Figma and get some help adding screenshots to the Component issues + creating new ones.  Then you and your fellow Hactober participants would have a solid starting point coming into next week!

If you're interested helping me out with this, lmk and I'll drop you an email to get you links kick the convo off! :smile:

**Review by jtfairbank — APPROVED** [review]
All looking good over here to me!

1. Did a longer site walkthrough to check that there were no import issues on a variety of pages ([CodeSee Recording](https://app.codesee.io/shared/128879f0-2d8f-11ec-82da-87f53a1ae192
)).
2. This revealed an issue with the "Where We Work" index page caused by a Region entry in contentful not having a map image, since the uploaded image did not meet some validation requirements (min-dimensions).  I resolved that on the data side in contentful by relaxing those requirements and publishing the existing image.
3. Tested it the Where We Work page again and it worked just fine once that property was set! ([CodeSee Recording](https://app.codesee.io/shared/c9f83430-2d90-11ec-b26f-9126c0278155))

**Comment by hola-soy-milk** [comment]
Thanks for reporting this issue with CodeSee Maps! I've reported it to the team. I suspect there might be an issue with new contributors.

**Pull request merged**
