### PR TITLE
Feat/821/long install

### LINKED ISSUE #821: First yarn install takes very long
### What happened?

Tried cloning the app from scratch and running yarn install.

Took about 5 minutes on a M1 macbook pro with decent internet connection

### Steps to reproduce

1. Clone the project
2. Run yarn install

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by JasonFritsche**
Resolves #821 

I've removed the following packages:
- `netlify-cli`
- `@graphql-codegen/cli`
- `@graphql-codegen/typescript`
- `@graphql-codegen/typescript-document-nodes`
- `sharp`
- `react-hook-form`
- `@types/node`
- `@types/testing-library__jest-dom`
- `@types/testing-library__react`
- `@types/react-table`
- `react-table`
- `react-multi-carousel`

I've added the following package:
- `ts-node` (Jest dependency)

Install times (starting with no `node_modules` and no `yarn.lock`) on my machine:
- Before: 3m 15s
- After 2m 37s

### CODE REVIEW

**Comment by JasonFritsche** [comment]
I installed and ran `gatsby-plugin-webpack-bundle-analyser-v2` ([link here](https://www.gatsbyjs.com/plugins/gatsby-plugin-webpack-bundle-analyser-v2/)) on a local branch and found that `three.js` is our largest dependency. 

Thoughts?

distribute-aid-webpack-analyzer-result

**Comment by JasonFritsche** [comment]
Looks like we have a step in our `test` job that runs the `gen-types` script. I removed `graphql-codegen` from the project. How should I proceed?
test-job-gen-types

**Comment by jtfairbank** [comment]
@JasonFritsche I think you can take `gen-types` out of `package.json` and the test workflow (`.github/workflows/test.yaml`).  I believe it is a holdover from when we used Contentful as our CMS.

Lmk if that breaks things tho!

**Comment by jtfairbank** [comment]
The dependency analyzer is super cool!  `three.js` is likely related to the 3D globe that we show on the home page.

I think it'd make more sense to replace it with a 2D map using the Nivo visualization library or something.  Maybe file a feature request for this, listing the dependency analysis results?

**Review by jtfairbank — APPROVED** [review]
Using [conventional comments](https://conventionalcomments.org/) code review style:

- praise: Great job @JasonFritsche!  Thanks so much!

**Pull request merged**
