### PR TITLE
Source Needs Assessment Data

### LINKED ISSUE #617: Source Needs Assessment Data
We need to source data from the needs assessment at build time in order to display it on the region pages.  See [this issue](https://github.com/distributeaid/needs-assessment-storage/issues/62) which documents the Needs Assessment Storage API for retrieving anonymized survey data.  Shoutout to @coderbyheart for the implementation! :partying_face: 

We'll be following this documentation to guide the implementation: https://www.gatsbyjs.com/docs/conceptual/data-fetching/#fetching-data-at-build-time

### Goals

* Filter needs assessment data by region & quarter.
* Auto-sum needs assessment data across regions or quarters?
* Expose needs assessment data nicely via Gatsby's GraphQL API.
* Control when new needs assessment data is ingested (so we don't use the next round of needs assessment data too early).
    - Note: this is a reach goal and will likely be moved to another issue as it may involve using the CMS (Forestry) to whitelist quarters.

### Checklist

- [x] Source the data using gatsby's `sourceNodes` hook.
- [x] Use gatsby's `createNode` function to create NeedsAssessmentSummary nodes.
- [x] Use gatsby's `createResolvers` hook to link NeedsAssessmentSummary nodes to their corresponding region.  Should be resolvable via `DANeed.place.region` and `DANeed.place.subregion`.  Every place has a region, most places have subregions but on occasion subregion might be set to `null` if the data applies to an entire region ("Lebanon") or the "Other" region was selected.
- [x] Write end-to-end tests to ensure that data is being ingested & exposed through Gatsby's graphql endpoint.

### Next Up

* [x] #649
  - #625 
  - #626
  - #627 
  - #628 
  - #629 
  - #630
  - #631 
  - #632 
  - #638
  - #648
* [ ] Show Needs Assessment visualizations on region pages.
* [ ] Create issues for a Needs Assessment page to show interactive visualizations.

### PR DESCRIPTION
**Pull request by jtfairbank**
Resolves #617 

Currently pulls in data for a single survey / quarter / region.

- [x] Whitelist surveys, pull data from all quarters / regions for each.  See https://github.com/distributeaid/needs-assessment-storage/discussions/90
- [x] Format data in a way that aligns w/ our category / item / age & gender / size & style breakdown.
- [x] Map Needs Assessment regions to Landing Site regions / subregions.
- [x] Error response handling for `fetch`.
- [x] Finish the other requirements from #617

### CODE REVIEW

**Comment by jtfairbank** [comment]
Hey @raae @coderbyheart need some advice here.  This one is all ready to go except for tests.  The problem is that it seems like unit testing w/ Jest is too low level and not that useful, but I can't find a way to easily write an e2e test with playwrite because we're not using the Needs Assessment data yet.

1. Is there an easy way to do an integration test so I can use the Gatsby graphql API to ensure the nodes are being created correctly?
2. Should I just skip testing at this level and make sure e2e tests are written when pages / components using the data are created, which should be testable with playwright?

**Comment by coderbyheart** [comment]
I would write a that for `sourceNeedsAssessmentData` which uses known good needs report data (committed as test data to the repo), to ensure that the data gets processes properly. For that move the data fetching code outside of the function, so it can be tested separately.

**Comment by jtfairbank** [comment]
Hey @coderbyheart still working on the tests.  In the meantime I merged `saga` in to get all the gatsby stuff in typescript.

Running into an error I can't figure out tho: in `/gatsby/source-nodes.ts` there's a reference error caused by using `fetch` even though I appear to be importing `node-fetch` correctly.  I've tried other ways of importing it (like dynamic imports, etc) but I'm stuck now.  Any ideas on why this might be happening?

**Comment by coderbyheart** [comment]
Where is the error you are seeing? For me, the `fetch` import looks fine.
image

Seeing all the other errors reminds me to turn on TypeScript checking for all TS code, not just `src`...

**Comment by coderbyheart** [comment]
I have some fixes in #762, which has no TS errors.

**Comment by coderbyheart** [comment]
Or are you talking about this issue?

```
error "gatsby-node.js" threw an error while running the onCreateNode lifecycle:

Cannot access 'y' before initialization

29 | ================================================================================
  30 | */
> 31 | export const onCreateNode: GatsbyNode['onCreateNode'] = (args) => {
     |              ^
  32 |   transformers.createRegionsFromMarkdown(args)
  33 |   transformers.createSubregionsFromMarkdown(args)
  34 |   transformers.createRoutesFromMarkdown(args)
    [distributeaid.org]/[bluebird]/js/release/promise.js:649:10
```

This seems to be caused by an issue when compiling TypeScript, however I could not immediately see why this is happening.

**Comment by coderbyheart** [comment]
So, I think I figured it out. Using [`cross-fetch`](https://www.npmjs.com/package/cross-fetch) solves the issue.

Additionally, I have refactored the code a bit to use `for ... of`, makes it a bit more readable I think.

Note that I observe that the node generation is run multiple times after start, I have not yet figured out what causes this.

**Comment by coderbyheart** [comment]
Build in #762 works now.

**Comment by coderbyheart** [comment]
My 2 cents on this: I think it's a complete overkill to source the needs assessment report through Gatsby's GraphQL API, because it is not needed there. After all, no pages are created from it, and the diagrams are not rendered server side.

Instead I would summarize the summaries to a JSON files that provide the neccessary, optimized data for the diagrams. Then on the diagram page, load those JSON files client side, when the page is loaded and the diagram needs to be rendered.

**Comment by jtfairbank** [comment]
@coderbyheart thanks for the help!  I resolved the issue of node creation continuing after the server started, it was a async/await mismatch that caused a race condition.

I agree that this might be overkill just for the visualizations, however the gatsby framework provides a consistent interface to source / transform / select our data.  And we're about to be able to load up shipment data so I'm interested in the ability to use those transformers to compare / contrast our shipping data w/ our needs data.

**Comment by jtfairbank** [comment]
@coderbyheart @hola-soy-milk This one's finally ready for review!

**Pull request merged**
