### PR TITLE
Remove unnecessary files

### PR DESCRIPTION
**Pull request by iulspop**
I noticed the 'where'  and 'package.lock.json' didn't belong in the project directory. I suggest we remove them.

### CODE REVIEW

**Review by jtfairbank — CHANGES_REQUESTED** [review]
Hey @iulspop, sorry for the super delayed review here!  Got tied up dealing with a whole bunch of complicated shipments the past couple months.  :sweat_smile: 

This looks great!  One last thing: could you add your name to the `CONTRIBUTORS.md` file and push that commit to this branch?  Thanks!

**Comment by ghost** [comment]
### Changes to your CodeSee Architecture Map:
[View a CodeSee Map of these changes](https://app.codesee.io/r/prs?id=4583&src=https%3A%2F%2Fgithub.com%2Fdistributeaid%2Fdistributeaid.org)

View [this PR diagram as an interactive map](https://app.codesee.io/r/prs?id=4583&src=https%3A%2F%2Fgithub.com%2Fdistributeaid%2Fdistributeaid.org)

View [more CodeSee Maps](https://app.codesee.io/r/maps?src=https%3A%2F%2Fgithub.com%2Fdistributeaid%2Fdistributeaid.org)

#### Legend
CodeSee Map Legend

**Comment by iulspop** [comment]
Hi @jtfairbank, I added my name to the contributor signatures. Is that all you needed?

**Comment by iulspop** [comment]
It looks like the files were already removed in the meantime. So this pull request is redundant, I'll just go ahead and close it :)

**Pull request closed without merging**
