### PR TITLE
Setup jest for testing

### LINKED ISSUE #4: Setup Jest For Testing
https://jestjs.io/

Haven't had time to setup testing yet- making sure this combo of tools works well for the team first.  Anyone can pick this up in the meantime!

### PR DESCRIPTION
**Pull request by khendrikse**
whale saying hello waving

I followed the guide by [Gatsby](https://www.gatsbyjs.com/docs/how-to/testing/unit-testing) to set up Jest. I also added one test (implementing [React Testing Library](https://testing-library.com/docs/react-testing-library/intro) to test it.

I did make some assumptions on the setup. Like naming the test `filename.test.js` which could also be set up differently of course :) 

This should close #4.

Curious what y'all think!

### CODE REVIEW

**Comment by khendrikse** [comment]
Just in case this PR is sufficient, I'd be curious to learn if there are specific tests that could be written to help out? :)

**Review by hola-soy-milk — APPROVED** [review]
Looks amazing to me, thank you so much @khendrikse!

This will allow us to start doing component level tests with mock data, unless I'm mistaken?

What do you think, @jtfairbank?

**Comment by khendrikse** [comment]
> Looks amazing to me, thank you so much @khendrikse!
> 
> This will allow us to start doing component level tests with mock data, unless I'm mistaken?
> 
> What do you think, @jtfairbank?

Yes! This would set up being able to do basic unit tests for helper functions and such. And with using React Testing Library it would be possible to make very specific user-focussed interaction tests for components ✨  so many possibilities.

**Comment by deammer** [comment]
Hi @khendrikse, thank you so much for adding a test framework!

Because this is the first time you're contributing to this repo, I'd like to ask you to check out our [contribution guide](https://github.com/distributeaid/distributeaid.org/blob/saga/CONTRIBUTORS.md). If that looks good to you, could you please add your name to the list? Once you do, we'll be able to merge this PR. Thank you again, and please let us know if you have any questions or concerns!

**Comment by khendrikse** [comment]
@deammer alright! I added my name :)

**Comment by jtfairbank** [comment]
@khendrikse sorry for the slow reply here- been pretty slammed on the aid shipments front but absolutely love to see you and other new contributors carrying the project forwards!!!  Up for tackling another issue?  Let me know what you're interested in!

@ramonh @deammer thanks for following up here to get this PR merged.  I'd say any of us can handle code reviews and merge PRs in.  Feel free to assign any to me that you think I should review specifically. :)

**Comment by hola-soy-milk** [comment]
Thanks so much, Taylor! Will do. So excited ot have your contributions in, @khendrikse 💜

**Comment by khendrikse** [comment]
@jtfairbank thanks! I was thinking of adding some tests :) it's good practice for me and might give some inspiration for others :)

**Pull request merged**
