### PR TITLE
fixed a11y for greece/index.html

### PR DESCRIPTION
**Pull request by preeformance**
Made changes so the accessibility for this page would go from 98% to 100% for lighthouse score, as mentioned in #661. 

After this PR, all pages should have a perfect accessibility score!

### CODE REVIEW

**Review by coderbyheart — CHANGES_REQUESTED** [review]
Please reformat source code with prettier

**Comment by coderbyheart** [comment]
Done. Thanks, again!

**Comment by preeformance** [comment]
Wow, were you able to get it to work?? I've been fighting with Prettier and it hasn't been cooperating. Every time I would format this page, the issue would pop back up and I've been trying to figure out why. I may have found a way that it all cooperates but now it's unclear if prettier actually reformatted it or not.

All of that to say, if it reverts when you deploy the new code, please let me know and I can make a PR for the altered version I mentioned above.

**Comment by coderbyheart** [comment]
`npx prettier --write ./` does the job, we also have this running [in a GitHub action](https://github.com/distributeaid/distributeaid.org/blob/df5676d3356f7365ea3aa0b3ebfb51eeeabe4336/.github/workflows/code-style.yaml#L38), and should happen [on commit on your local repo](https://github.com/distributeaid/distributeaid.org/blob/745e221f2af57b96b7209d94701e84ab92a9ae4c/.husky/pre-commit#L4).

**Pull request merged**
