### PR TITLE
feat: Added the image component and calling from boardmembers component

### PR DESCRIPTION
**Pull request by fedechaves**
This makes progress in Issue #584.

### CODE REVIEW

**Comment by jtfairbank** [comment]
Hey @coderbyheart or @JasonFritsche can you help me and @fedechaves debug the commented out tests in `/src/components/image/image.test.tsx`?  I don't understand why it says that the div is visible when the `hidden` class name is applied before / after hover.  If you uncomment either of the assertions they both result in the same test failure.

**Comment by coderbyheart** [comment]
Can we avoid implementing hover-based features, please? It only works on device that have a mouse input, and there are usually no good alternatives for touch based devices.

**Comment by fedechaves** [comment]
Thank you, @coderbyheart, for the recommendation.

**Comment by fedechaves** [comment]
Hi  @wwwwwlwwwww ! Could you give us a hand on how to display the caption of the image? Do you want us to keep it embedded in the image, or maybe we should set it up below? 

Thanks in advance!

**Comment by wwwwwlwwwww** [comment]
@fedechaves This is a good question.  In future iterations, we might want to have multiple options for display depending on some parameter in our CMS.  For this first iteration, I think the following should be more than adequate:
 * If the caption field is blank or empty, do nothing; no need for an empty space where a caption would otherwise go.
 * Else display the caption below the image, aligned either left, right, or centre depending on the alignmentCaption field (default would be centre align).

I imagine that alt text should be embedded in the image, though I'm not sure about what best practices are for doing that in a way that screen readers can appropriately handle the alt text.  You didn't ask about alt text though, so I won't belabor this point

**Review by jtfairbank — DISMISSED** [review]
praise: Thanks so much for sticking with this one Fede!  It was great seeing all the progress you made between each code jam!

**Comment by fedechaves** [comment]
thanks to you @jtfairbank for the patience, guidance, and creation of such a great place to collab and learn!

**Comment by jtfairbank** [comment]
Hey @fedechaves I think you forgot to push the changes you made this morning.  Can you try to get back on that gitpod and push them?

You should use "git push --force" because I resolved some merge issues already, you'll want to overwrite my changes.

**Comment by fedechaves** [comment]
@jtfairbank done!

**Review by jtfairbank — APPROVED** [review]

**Pull request merged**
