### PR TITLE
Integrate social icon SVGs

### PR DESCRIPTION
**Pull request by hola-soy-milk**
CodeSee Recording:
https://app.codesee.io/shared/3cb932a0-5918-11ec-a6dd-192c1888c6aa

### CODE REVIEW

**Comment by coderbyheart** [comment]
@ramonh are you the creator of these icons?

**Comment by hola-soy-milk** [comment]
No, they're from Figma!

**Comment by coderbyheart** [comment]
So, how are they licensed?

**Comment by hola-soy-milk** [comment]
Good question. They're from the design on Figma, so I figured they were made by Design. I'll find out!

**Comment by coderbyheart** [comment]
Yes, please. We can't add work from others authors to our repo without properly licensing it.

**Comment by hola-soy-milk** [comment]
Thanks for pointing this out! I'm on it.

**Pull request merged**
